[font]
normal = { family = "Iosevka", style = "Bold" }
italic = { family = "Iosevka", style = "Italic" }
size   = 22

[colors]
cursor = { text = "#FFFFFF", cursor = "#EE1212" }
[colors.primary]
background = "#000000"

[env]
TERM = "xterm-256color"
